import type { 
  Contact, 
  Quotation, 
  Order, 
  Product, 
  Warehouse, 
  Invoice, 
  Partner, 
  User, 
  Company,
  Plan,
  Additional,
  Package,
  Entitlements,
  PlanType,
  PlanLimits
} from "./types"

// Planos
export const PLANS: Plan[] = [
  {
    id: "starter",
    name: "Starter",
    price: 249,
    yearlyPrice: 2490,
    features: [
      "Gestão de contatos",
      "Orçamentos ilimitados",
      "Até 100 pedidos/mês",
      "1 armazém",
      "Suporte por email",
    ],
    limits: {
      contacts: 500,
      quotations: "unlimited",
      orders: 100,
      warehouses: 1,
      products: 200,
      users: 2,
      partners: 5,
      apiRequests: 1000,
    }
  },
  {
    id: "pro",
    name: "Pro",
    price: 449,
    yearlyPrice: 4490,
    features: [
      "Tudo do Starter",
      "Pedidos ilimitados",
      "Até 3 armazéns",
      "Módulo financeiro",
      "Relatórios avançados",
      "Suporte prioritário",
    ],
    limits: {
      contacts: 2000,
      quotations: "unlimited",
      orders: "unlimited",
      warehouses: 3,
      products: 1000,
      users: 5,
      partners: 20,
      apiRequests: 10000,
    }
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 749,
    yearlyPrice: 7490,
    features: [
      "Tudo do Pro",
      "Armazéns ilimitados",
      "Módulo contábil",
      "Programa de parceiros",
      "API completa",
      "Suporte 24/7",
    ],
    limits: {
      contacts: "unlimited",
      quotations: "unlimited",
      orders: "unlimited",
      warehouses: "unlimited",
      products: "unlimited",
      users: 20,
      partners: "unlimited",
      apiRequests: "unlimited",
    }
  },
  {
    id: "develop",
    name: "Develop",
    price: 0,
    yearlyPrice: 0,
    features: [
      "Acesso total",
      "Ambiente de testes",
      "Para desenvolvedores",
    ],
    limits: {
      contacts: "unlimited",
      quotations: "unlimited",
      orders: "unlimited",
      warehouses: "unlimited",
      products: "unlimited",
      users: "unlimited",
      partners: "unlimited",
      apiRequests: "unlimited",
    }
  }
]

// Adicionais
export const ADDITIONALS: Additional[] = [
  { id: "whatsapp_bot", name: "Chatbot WhatsApp", monthlyPrice: 99, description: "Automação de atendimento via WhatsApp", category: "monthly" },
  { id: "pix_integration", name: "Integração PIX", monthlyPrice: 49, transactionFee: 0.99, description: "Receba pagamentos via PIX automaticamente", category: "monthly" },
  { id: "nfse_integration", name: "Emissão de NFS-e", monthlyPrice: 79, description: "Emissão automática de notas fiscais", category: "monthly" },
  { id: "extra_warehouse", name: "Armazém Extra", monthlyPrice: 39, description: "Adicione mais um armazém ao seu plano", category: "monthly" },
  { id: "extra_users", name: "Pacote 5 Usuários", monthlyPrice: 59, description: "Adicione mais 5 usuários ao sistema", category: "monthly" },
  { id: "custom_domain", name: "Domínio Personalizado", monthlyPrice: 29, setupPrice: 99, description: "Use seu próprio domínio", category: "monthly" },
  { id: "data_migration", name: "Migração de Dados", setupPrice: 499, description: "Migração completa dos seus dados antigos", category: "setup" },
  { id: "custom_training", name: "Treinamento Personalizado", setupPrice: 299, description: "Treinamento exclusivo para sua equipe", category: "setup" },
  { id: "priority_onboarding", name: "Onboarding Prioritário", setupPrice: 199, description: "Configuração assistida em até 24h", category: "setup" },
]

// Pacotes
export const PACKAGES: Package[] = [
  { id: "automation", name: "Pacote Automação", price: 199, discount: "20%", includes: ["whatsapp_bot", "pix_integration"] },
  { id: "fiscal", name: "Pacote Fiscal", price: 149, discount: "15%", includes: ["nfse_integration", "custom_domain"] },
  { id: "scale", name: "Pacote Escala", price: 129, discount: "25%", includes: ["extra_warehouse", "extra_users"] },
]

// Função para obter entitlements baseados no plano
export function getEntitlements(planId: PlanType, additionals: string[] = [], packages: string[] = []): Entitlements {
  const plan = PLANS.find(p => p.id === planId) || PLANS[0]
  
  const baseFeatures = {
    contacts: true,
    quotations: true,
    orders: planId !== "starter" || additionals.length > 0,
    logistics: planId !== "starter",
    inventory: true,
    warehouses: true,
    stock: planId !== "starter",
    financial: planId !== "starter",
    accounting: planId === "enterprise" || planId === "develop",
    partners: planId === "enterprise" || planId === "develop",
    reports: planId !== "starter",
    api: planId === "enterprise" || planId === "develop",
    whatsappBot: additionals.includes("whatsapp_bot") || packages.includes("automation"),
    multiUsers: plan.limits.users !== 1,
    customBranding: planId === "enterprise" || planId === "develop" || additionals.includes("custom_domain"),
    prioritySupport: planId !== "starter",
  }

  return {
    plan: planId,
    additionals,
    packages,
    features: baseFeatures,
    limits: plan.limits,
  }
}

// Dados mockados
export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "Empresa Festa Feliz",
    email: "contato@festafeliz.com.br",
    phone: "(11) 99999-1234",
    type: "client",
    document: "12.345.678/0001-90",
    address: "Rua das Flores, 123",
    city: "São Paulo",
    state: "SP",
    createdAt: "2024-01-15",
    updatedAt: "2024-03-20",
  },
  {
    id: "c2",
    name: "Maria Santos",
    email: "maria.santos@gmail.com",
    phone: "(11) 97777-9012",
    type: "client",
    document: "123.456.789-00",
    address: "Rua Augusta, 500",
    city: "São Paulo",
    state: "SP",
    createdAt: "2024-02-10",
    updatedAt: "2024-03-18",
  },
  {
    id: "c3",
    name: "Buffet Sabor & Arte",
    email: "contato@saborarte.com.br",
    phone: "(11) 96666-3456",
    type: "partner",
    document: "98.765.432/0001-10",
    address: "Rua dos Eventos, 789",
    city: "São Paulo",
    state: "SP",
    createdAt: "2024-01-05",
    updatedAt: "2024-03-22",
  },
  {
    id: "c4",
    name: "João Silva",
    email: "joao.silva@email.com",
    phone: "(11) 95555-7890",
    type: "client",
    address: "Av. Paulista, 1000",
    city: "São Paulo",
    state: "SP",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-25",
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Cadeira Tiffany Cristal",
    description: "Cadeira de acrílico transparente, estilo clássico",
    category: "Cadeiras",
    costPrice: 150,
    rentalPrice: 35,
    stockQuantity: 200,
    minStock: 50,
    unit: "unidade",
    warehouseId: "w1",
    warehouseName: "Armazém Central",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-03-20",
  },
  {
    id: "p2",
    name: "Mesa Redonda 1.5m",
    description: "Mesa redonda para 10 lugares",
    category: "Mesas",
    costPrice: 300,
    rentalPrice: 85,
    stockQuantity: 50,
    minStock: 15,
    unit: "unidade",
    warehouseId: "w1",
    warehouseName: "Armazém Central",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-03-20",
  },
  {
    id: "p3",
    name: "Toalha Branca Redonda",
    description: "Toalha de mesa em tecido oxford",
    category: "Toalhas",
    costPrice: 25,
    rentalPrice: 15,
    stockQuantity: 300,
    minStock: 100,
    unit: "unidade",
    warehouseId: "w1",
    warehouseName: "Armazém Central",
    isActive: true,
    createdAt: "2024-01-01",
    updatedAt: "2024-03-20",
  },
]

export const mockWarehouses: Warehouse[] = [
  {
    id: "w1",
    name: "Armazém Central",
    address: "Rua Industrial, 500",
    city: "São Paulo",
    state: "SP",
    capacity: 1000,
    usedCapacity: 650,
    isMain: true,
    responsibleName: "Carlos Souza",
    responsiblePhone: "(11) 98888-1234",
    createdAt: "2024-01-01",
    updatedAt: "2024-03-20",
  },
  {
    id: "w2",
    name: "Armazém Zona Norte",
    address: "Av. Norte, 1200",
    city: "São Paulo",
    state: "SP",
    capacity: 500,
    usedCapacity: 280,
    isMain: false,
    responsibleName: "Ana Lima",
    responsiblePhone: "(11) 97777-5678",
    createdAt: "2024-02-15",
    updatedAt: "2024-03-18",
  },
]

export const mockQuotations: Quotation[] = [
  {
    id: "Q-198",
    contactId: "c4",
    contactName: "João Silva",
    items: [
      { productId: "p1", productName: "Cadeira Tiffany Cristal", quantity: 10, unitPrice: 35, subtotal: 350 },
    ],
    subtotal: 350,
    discount: 0,
    total: 350,
    status: "sent",
    validUntil: "2024-04-15",
    sentVia: "whatsapp",
    createdAt: "2024-03-25",
    updatedAt: "2024-03-25",
  },
  {
    id: "Q-197",
    contactId: "c1",
    contactName: "Empresa Festa Feliz",
    items: [
      { productId: "p1", productName: "Cadeira Tiffany Cristal", quantity: 50, unitPrice: 35, subtotal: 1750 },
      { productId: "p2", productName: "Mesa Redonda 1.5m", quantity: 10, unitPrice: 85, subtotal: 850 },
    ],
    subtotal: 2600,
    discount: 100,
    total: 2500,
    status: "approved",
    validUntil: "2024-04-10",
    sentVia: "email",
    createdAt: "2024-03-20",
    updatedAt: "2024-03-22",
  },
]

export const mockOrders: Order[] = [
  {
    id: "PED-4521",
    quotationId: "Q-197",
    contactId: "c1",
    contactName: "Empresa Festa Feliz",
    contactPhone: "(11) 99999-1234",
    items: [
      { productId: "p1", productName: "Cadeira Tiffany Cristal", quantity: 50, unitPrice: 35, subtotal: 1750 },
      { productId: "p2", productName: "Mesa Redonda 1.5m", quantity: 10, unitPrice: 85, subtotal: 850 },
      { productId: "p3", productName: "Toalha Branca Redonda", quantity: 10, unitPrice: 15, subtotal: 150 },
    ],
    subtotal: 2750,
    deliveryFee: 100,
    discount: 100,
    total: 2750,
    status: "confirmed",
    paymentStatus: "pending",
    deliveryAddress: "Rua das Flores, 123 - São Paulo, SP",
    deliveryDate: "2024-04-05",
    deliveryTime: "08:00",
    deliveryPriority: "commercial_hours",
    pickupDate: "2024-04-06",
    pickupTime: "20:00",
    deliveryPersonId: "d1",
    deliveryPersonName: "Carlos",
    createdAt: "2024-03-22",
    updatedAt: "2024-03-25",
  },
  {
    id: "PED-4520",
    contactId: "c2",
    contactName: "Maria Santos",
    contactPhone: "(11) 97777-9012",
    items: [
      { productId: "p1", productName: "Cadeira Tiffany Cristal", quantity: 20, unitPrice: 35, subtotal: 700 },
      { productId: "p2", productName: "Mesa Redonda 1.5m", quantity: 5, unitPrice: 85, subtotal: 425 },
    ],
    subtotal: 1125,
    deliveryFee: 50,
    discount: 0,
    total: 1175,
    status: "completed",
    paymentStatus: "paid",
    deliveryAddress: "Rua Augusta, 500 - São Paulo, SP",
    deliveryDate: "2024-03-20",
    deliveryTime: "09:00",
    deliveryPriority: "custom_period",
    pickupDate: "2024-03-20",
    pickupTime: "18:00",
    deliveryPersonId: "d2",
    deliveryPersonName: "João",
    createdAt: "2024-03-15",
    updatedAt: "2024-03-20",
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "FAT-001",
    orderId: "PED-4521",
    contactId: "c1",
    contactName: "Empresa Festa Feliz",
    amount: 2750,
    paidAmount: 0,
    status: "pending",
    dueDate: "2024-04-10",
    createdAt: "2024-03-22",
    updatedAt: "2024-03-22",
  },
  {
    id: "FAT-002",
    orderId: "PED-4520",
    contactId: "c2",
    contactName: "Maria Santos",
    amount: 1175,
    paidAmount: 1175,
    status: "paid",
    dueDate: "2024-03-25",
    paidAt: "2024-03-20",
    paymentMethod: "pix",
    createdAt: "2024-03-15",
    updatedAt: "2024-03-20",
  },
]

export const mockPartners: Partner[] = [
  {
    id: "pr1",
    name: "Buffet Sabor & Arte",
    companyName: "Buffet Sabor & Arte Ltda",
    email: "contato@saborarte.com.br",
    phone: "(11) 96666-3456",
    role: "both",
    status: "active",
    totalOrders: 15,
    totalRevenue: 12500,
    balance: 2500,
    createdAt: "2024-01-05",
    updatedAt: "2024-03-22",
  },
]

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Admin DZ",
    email: "admin@dzlocadora.com.br",
    phone: "(11) 99999-0000",
    role: "admin",
    isActive: true,
    createdAt: "2024-01-01",
  },
  {
    id: "u2",
    name: "Carlos Souza",
    email: "carlos@dzlocadora.com.br",
    phone: "(11) 98888-1234",
    role: "delivery",
    isActive: true,
    createdAt: "2024-01-15",
  },
]

export const mockCompany: Company = {
  id: "comp1",
  name: "DZ Locadora de Materiais para Festas",
  tradeName: "DZ Locadora",
  document: "12.345.678/0001-90",
  email: "contato@dzlocadora.com.br",
  phone: "(11) 3333-4444",
  address: "Rua Industrial, 500",
  city: "São Paulo",
  state: "SP",
  zipCode: "01234-567",
  plan: "pro",
  additionals: ["pix_integration"],
  packages: [],
  workingHours: {
    monday: { isOpen: true, morningStart: "08:00", morningEnd: "12:00", afternoonStart: "13:00", afternoonEnd: "17:00" },
    tuesday: { isOpen: true, morningStart: "08:00", morningEnd: "12:00", afternoonStart: "13:00", afternoonEnd: "17:00" },
    wednesday: { isOpen: true, morningStart: "08:00", morningEnd: "12:00", afternoonStart: "13:00", afternoonEnd: "17:00" },
    thursday: { isOpen: true, morningStart: "08:00", morningEnd: "12:00", afternoonStart: "13:00", afternoonEnd: "17:00" },
    friday: { isOpen: true, morningStart: "08:00", morningEnd: "12:00", afternoonStart: "13:00", afternoonEnd: "17:00" },
    saturday: { isOpen: true, morningStart: "08:00", morningEnd: "12:00" },
    sunday: { isOpen: false },
  },
  createdAt: "2024-01-01",
}
